Logger ut feil ved kall til inntektskomponenten
navikt/ft-inntektsmelding pull request #305
Opened 2024-12-17 11:46 UTC by pekern

2025-01-08 09:03 UTC, mrsladek requested changes

2025-01-08 09:03 UTC, mrsladek commented on src/main/java/no/nav/familie/inntektsmelding/integrasjoner/inntektskomponent/InntektTjeneste.java
> +            LOG.warn("Nedetid i inntektskomponenten, returnerer tomme måneder uten snittlønn til frontend. Fikk feil %s", e);
Trenger vi hele exception eller er det nok med kun e.getMessage() ? Bruk gjerne {} istf %s. Tror %s vil ikke virke ut av boksen heler.

2025-01-08 09:45 UTC, pekern commented on src/main/java/no/nav/familie/inntektsmelding/integrasjoner/inntektskomponent/InntektTjeneste.java
> +            LOG.warn("Nedetid i inntektskomponenten, returnerer tomme måneder uten snittlønn til frontend. Fikk feil %s", e);
Trenger nok bare message ja, kan endre :)

2025-01-09 11:47 UTC, mrsladek approved these changes

2025-01-09 11:58 UTC, merged